--1

SELECT
    *
FROM PACIENT P
JOIN CONSULTATIE C ON P.ID_PACIENT=C.ID_PACIENT
JOIN PRESCRIPTIE PR ON PR.ID_CONSULTATIE=C.ID_CONSULTATIE
JOIN MEDICAMENT M ON M.ID_MEDICAMENT=PR.ID_MEDICAMENT
WHERE UPPER(M.NUME)='IBUPROFEN';

--2

SELECT
    *
FROM (
        SELECT
            D.ID_DOCTOR, D.NUME, D.PRENUME, D.ID_SECTIE, D.SALARIU, COUNT(C.ID_CONSULTATIE)
        FROM CONSULTATIE C
        JOIN DOCTOR D ON D.ID_DOCTOR=C.ID_DOCTOR
        GROUP BY D.ID_DOCTOR, D.NUME, D.PRENUME, D.ID_SECTIE, D.SALARIU
        HAVING COUNT(C.ID_CONSULTATIE)>=2
        ORDER BY D.SALARIU DESC, COUNT(C.ID_CONSULTATIE)
        )
WHERE ROWNUM<=2;

--3

SELECT DISTINCT
    S.ID_SECTIE,D.NUME, D.PRENUME, D.SALARIU
FROM DOCTOR D
JOIN SECTIE S ON S.ID_SECTIE=D.ID_SECTIE
GROUP BY S.ID_SECTIE, D.NUME, D.PRENUME, D.SALARIU
HAVING D.SALARIU>=ALL(
    SELECT
        D1.SALARIU
    FROM DOCTOR D1
    WHERE D1.ID_SECTIE=S.ID_SECTIE
    )
UNION
SELECT
    S1.ID_SECTIE,'-','-',0
FROM SECTIE S1
WHERE S1.ID_SECTIE NOT IN(
    SELECT
        D2.ID_SECTIE
    FROM DOCTOR D2
    );
    
--4

SELECT
    *
FROM PACIENT P
WHERE P.ID_SECTIE IN(
    SELECT
        S1.ID_SECTIE
    FROM CONSULTATIE C1
    JOIN PACIENT P1 ON P1.ID_PACIENT=C1.ID_PACIENT
    JOIN SECTIE S1 ON S1.ID_SECTIE=P1.ID_SECTIE
    GROUP BY S1.ID_SECTIE
    HAVING COUNT(C1.ID_CONSULTATIE)<=ALL(
        SELECT
            COUNT(C2.ID_CONSULTATIE)
        FROM CONSULTATIE C2
        JOIN PACIENT P2 ON P2.ID_PACIENT=C2.ID_PACIENT
        JOIN SECTIE S2 ON S2.ID_SECTIE=P2.ID_SECTIE
        GROUP BY S2.ID_SECTIE
        )
    );
    